apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  containers:
        - name: python-app
          image: jagratimishra1415/python-app:latest 
          ports:
            - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
